# Bigram Typing Analysis Configuration

# Data settings
data:
  input_dir: "/Users/arno/Downloads/osf/output"
  filtered_data_file: "tables/processed_data/processed_bigram_data.csv"
  
# Analysis parameters
analysis:
  # Participant-level settings
  min_trials_per_participant: 10
  outlier_threshold_sd: 3.0
  min_bigram_occurrences: 5
  
  # Statistical settings
  bootstrap_iterations: 1000
  confidence_level: 0.95
  
  # Time difference analysis
  max_time_ms: 3000
  normalize_method: "median"  # Options: median, mean
  n_quantiles: 5
  
  # Frequency analysis
  frequency_transform: "log10"  # Options: log10, log2, none
  
# Output settings
output:
  base_dir: "/Users/arno/Downloads/osf/output/plots"
  subdirs:
    typing_time_vs_preference: "typing_time_vs_preference"
    typing_time_vs_frequency: "typing_time_vs_frequency"
    preference_prediction: "preference_prediction"
  
# Logging settings
logging:
  level: "INFO"
  file: "bigram_analysis.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Visualization settings
visualization:
  dpi: 300
  figsize: [10, 6]
  style: "default"
  colors:
    primary: "#1f77b4"
    secondary: "#ff7f0e"
    error_bars: "#2ca02c"
    regression: "#9467bd"
    
  plots:
    time_diff:
      figsize: [12, 8]
      alpha: 0.5
      grid_alpha: 0.3
      bins: 30
      confidence_alpha: 0.8
      error_alpha: 0.2
      error_capsize: 5
      
    frequency:
      figsize: [12, 8]
      scatter_alpha: 0.6
      error_alpha: 0.2
      regression_alpha: 0.7
      label_fontsize: 8
      grid_alpha: 0.3
      
    prediction:
      figsize: [10, 6]
      hist_bins: 20
      bar_alpha: 0.8
      error_capsize: 5
      grid_alpha: 0.3
      
    distribution:
      figsize: [15, 10]
      grid_alpha: 0.3
      legend_fontsize: 10
      title_fontsize: 16
      label_fontsize: 12